// vue-scheduler/src/components/room_status_components/progress_bar_components/ProgressBar.vue
<script setup lang="ts">
import RadialSeparators from './RadialSeparators.vue';
import LoadingComponent from '@/components/common_components/LoadingComponent.vue';

interface ProgressBarProps {
  value: number;
  isBooked: boolean;
  isLoading: boolean;
  isError: boolean;
}
const props = defineProps<ProgressBarProps>();
const { value, isBooked, isLoading, isError } = props;
</script>

<template>
  <!-- Wrap circular progress bar -->
  <div :class="$style.progressBar">
    <!-- <RadialSeparators :count="60" /> -->
    <div :class="$style.statusContainer">
      <LoadingComponent v-if="isLoading" />
      <p v-else-if="isError" :class="$style.errorMsg">An error has occurred!</p>
      <p v-else-if="isBooked" :class="$style.inProgress">Meeting in progress</p>
      <p v-else :class="$style.available">Available</p>
    </div>
  </div>
</template>

<style lang="scss" module>
.progressBar {
  width: 75%;
  aspect-ratio: 1/1;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  border-radius: 50%;
  overflow: hidden;

  .statusContainer {
    z-index: 2;

    p {
      font-size: 32px;
      font-weight: bold;
    }

    .available {
      color: var(--light-green);
    }

    .inProgress {
      color: var(--dark-red);
    }

    .errorMsg {
      color: var(--light-red);
      font-size: 28px;
    }
  }
}
</style>

// react-scheduler/src/components/room_status/progress_bar/ProgressBar.tsx
import {
  CircularProgressbarWithChildren,
  buildStyles,
} from "react-circular-progressbar";
import { LoadingComponent } from "../../shared_components/loading_component/LoadingComponent";
import { RadialSeparators } from "./radial_separators/RadialSeparators";
import styles from "./ProgressBar.module.scss";

interface ProgressBarProps {
  value: number;
  isBooked: boolean;
  isLoading: boolean;
  isError: boolean;
}

export const ProgressBar = (props: ProgressBarProps) => {
  const { value, isBooked, isLoading, isError } = props;
  const strokeWidth = 5;

  const handleRoomStatusMessages = (): JSX.Element => {
    if (isLoading) return <LoadingComponent />;
    if (isError)
      return <p className={styles.errorMsg}>An error has occurred!</p>;
    if (isBooked)
      return <p className={styles.inProgress}>Meeting in progress</p>;
    return <p className={styles.available}>Available</p>;
  };

  return (
    <div className={styles.progressBar}>
      <CircularProgressbarWithChildren
        value={value}
        strokeWidth={strokeWidth}
        styles={buildStyles({
          strokeLinecap: "butt",
          pathColor: "#2D3D46",
          trailColor: "#ACE1F0",
        })}
        className={styles.progressBarWithChildren}
      >
        <RadialSeparators count={60} />
        <div className={styles.statusContainer}>
          {handleRoomStatusMessages()}
        </div>
      </CircularProgressbarWithChildren>
    </div>
  );
};
