// react-scheduler/src/components/scheduler/scheduler_component/Scheduler.tsx
import { useEffect } from "react";
import { Timeline } from "../timeline/Timeline";
import { Indicator } from "../indicator/Indicator";
import { EventInfo } from "../../../types/EventInfo";
import styles from "./Scheduler.module.scss";
import {
  calculateSingularEventOffset,
  getLastConcurrentEventIdx,
  indicatorId,
} from "../../../helpers/scheduler_helper";
import { SingularEventWrapper } from "../event_components/singular_event_wrapper/SingularEventWrapper";
import { GroupEventWrapper } from "../event_components/group_event_wrapper/GroupEventWrapper";

interface SchedulerProps {
  events: EventInfo[];
}

export const Scheduler = (props: SchedulerProps) => {
  const { events } = props;

  useEffect(() => {
    // "autofocus" on the indicator
    const indicatorComponent = document.getElementById(indicatorId);
    if (indicatorComponent)
      indicatorComponent.scrollIntoView({
        behavior: "smooth",
        block: "nearest",
        inline: "start",
      });
  }, []);

  const generateEvents = (): JSX.Element[] => {
    const generatedEvents: JSX.Element[] = [];

    let idxOfLastConcurrentElement = -1;
    for (let i = 0; i < events.length; i++) {
      if (i <= idxOfLastConcurrentElement) continue;
      const response = getLastConcurrentEventIdx(i, events);
      if (response.lastIdx !== -1) {
        idxOfLastConcurrentElement = response.lastIdx;
        generatedEvents.push(
          <GroupEventWrapper
            allEventsInfo={events}
            groupIndices={response.allIndeces}
            key={`group-events-${response.allIndeces[0]}`}
          />
        );
      } else {
        const eventDimensions = calculateSingularEventOffset(events[i]);
        generatedEvents.push(
          <SingularEventWrapper
            topOffset={eventDimensions.topOffset}
            eventHeight={eventDimensions.eventHeight}
            eventInfo={events[i]}
            key={`event-${i}`}
          />
        );
      }
    }

    return generatedEvents;
  };

  return (
    <div className={styles.scheduler}>
      <Indicator />
      <Timeline />
      {generateEvents()}
    </div>
  );
};

// vue-scheduler/src/components/scheduler_components/SchedulerComponent.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue';
import IndicatorComponent from './IndicatorComponent.vue';
import TimelineComponent from './timeline_components/TimelineComponent.vue';
import SingularEventWrapper from './event_components/SingularEventWrapper.vue';
import GroupEventWrapper from './event_components/GroupEventWrapper.vue';
import {
  calculateSingularEventOffset,
  getLastConcurrentEventIdx,
  indicatorId,
  type EventOffset
} from '@/helpers/scheduler_helper';
import type { EventInfo } from '@/types/EventInfo';

interface SingularEventsInfo {
  eventDimensions: EventOffset;
  eventInfo: EventInfo;
  eventIdx: number;
}

interface GroupEventsInfo {
  allEventsInfo: EventInfo[];
  groupIndeces: number[];
}

interface SchedulerProps {
  events: EventInfo[];
}
const props = defineProps<SchedulerProps>();

// Scroll the IndicatorComponent into view
onMounted(() => {
  const indicatorComponent = document.getElementById(indicatorId);
  if (indicatorComponent)
    indicatorComponent.scrollIntoView({
      behavior: 'smooth',
      block: 'nearest',
      inline: 'start'
    });
});

const eventData = computed<{
  singularEventsInfo: SingularEventsInfo[];
  groupEventsInfo: GroupEventsInfo[];
}>(() => {
  const singularEvents: SingularEventsInfo[] = [];
  const groupEvents: GroupEventsInfo[] = [];

  let idxOfLastConcurrentElement = -1;
  for (let i = 0; i < props.events.length; i++) {
    if (i <= idxOfLastConcurrentElement) continue;
    const response = getLastConcurrentEventIdx(i, props.events);
    if (response.lastIdx !== -1) {
      idxOfLastConcurrentElement = response.lastIdx;
      groupEvents.push({
        allEventsInfo: props.events,
        groupIndeces: response.allIndeces
      });
    } else {
      const eventDimensions = calculateSingularEventOffset(props.events[i]);
      singularEvents.push({
        eventDimensions: eventDimensions,
        eventInfo: props.events[i],
        eventIdx: i
      });
    }
  }

  return { singularEventsInfo: singularEvents, groupEventsInfo: groupEvents };
});
</script>

<template>
  <div :class="$style.scheduler">
    <IndicatorComponent />
    <TimelineComponent />
    <SingularEventWrapper
      v-for="singular in eventData.singularEventsInfo"
      :key="`event-${singular.eventIdx}`"
      :eventInfo="singular.eventInfo"
      :topOffset="singular.eventDimensions.topOffset"
      :eventHeight="singular.eventDimensions.eventHeight"
    />
    <GroupEventWrapper
      v-for="group in eventData.groupEventsInfo"
      :key="`group-events-${group.groupIndeces[0]}`"
      :allEventsInfo="group.allEventsInfo"
      :groupIndeces="group.groupIndeces"
    />
  </div>
</template>

<style lang="scss" module>
.scheduler {
  overflow: auto;
  margin: auto;
  position: relative;
  color: var(--white);
  width: 100%;
  height: 600px;

  &::-webkit-scrollbar {
    width: 5px;
  }

  &::-webkit-scrollbar-thumb {
    background-color: var(--dark-blue);
    border-radius: 10px;

    &:hover {
      background-color: var(--light-blue);
    }
  }
}
</style>
