// react-scheduler/src/components/shared_components/button_component/Button.tsx
import styles from "./Button.module.scss";

interface ButtonProps {
  content: string;
  onClick: () => void;
  theme: "purple" | "green";
  disabled: boolean;
}

export const Button = (props: ButtonProps) => {
  const { content, theme, disabled, onClick } = props;

  const handleClick = () => {
    if (disabled) return;
    onClick();
  };
  return (
    <div
      className={`${styles.button} ${disabled ? styles.isDisabled : ""}`}
      onClick={handleClick}
      data-theme={theme}
    >
      {content}
    </div>
  );
};

// vue-scheduler/src/components/common_components/ButtonComponent.vue
<script setup lang="ts">
interface ButtonProps {
  content: string;
  theme: 'purple' | 'green';
  disabled: boolean;
}

const props = defineProps<ButtonProps>();
const emit = defineEmits(['btn-click']);
</script>

<template>
  <div
    :class="[$style.button, props.disabled ? $style.isDisabled : '']"
    @click="emit('btn-click', 'im the payload')"
    :data-theme="props.theme"
  >
    {{ props.content }}
  </div>
</template>

<style lang="scss" module>
.button {
  display: block;
  text-align: center;
  padding: 1rem;
  border-radius: 20px;
  height: fit-content;
  cursor: pointer;
  color: var(--white);

  &[data-theme='purple'] {
    background-color: var(--light-purple);

    &:hover {
      background-color: var(--dark-purple);
    }

    &.isDisabled {
      background-color: var(--dark-purple);
      cursor: not-allowed;
    }
  }

  &[data-theme='green'] {
    background-color: var(--light-green);

    &:hover {
      background-color: var(--dark-green);
    }

    &.isDisabled {
      background-color: var(--dark-green);
      cursor: not-allowed;
    }
  }
}
</style>
