// vue-scheduler/src/components/modal_components/MeetingInfoModal.vue
<script setup lang="ts">
import type { EventInfo } from '@/types/EventInfo';
import ModalSkeleton from './ModalSkeleton.vue';
import { format } from 'date-fns';

interface MeetingInfoModalProps {
  eventInfo: EventInfo;
}

const props = defineProps<MeetingInfoModalProps>();
const emits = defineEmits(['modal-close']);
</script>

<template>
  <ModalSkeleton :title="props.eventInfo.subject" @modal-close="emits('modal-close')">
    <template v-slot:children>
      <h3 :class="$style.subtitleInfo">
        Start:<span>{{ format(props.eventInfo.startTime, 'HH:mm') }}</span>
      </h3>
      <h3 :class="$style.subtitleInfo">
        End:<span>{{ format(props.eventInfo.endTime, 'HH:mm') }}</span>
      </h3>
      <h3 :class="$style.subtitleInfo">
        Organizer:<span>{{ props.eventInfo.organizer }}</span>
      </h3>
    </template>
  </ModalSkeleton>
</template>

<style lang="scss" module>
.subtitleInfo {
  color: var(--light-blue);
  padding: 5px;

  span {
    color: var(--white);
    margin-left: 5px;
  }
}
</style>

// react-scheduler/src/components/modals/meeting_info_modal/MeetingInfoModal.tsx
import { format } from "date-fns";
import { EventInfo } from "../../../types/EventInfo";
import { ModalSkeleton } from "../modal_skeleton/ModalSkeleton";
import styles from "./MeetingInfoModal.module.scss";

interface MeetingInfoModalProps {
  eventInfo: EventInfo;
  handleModalClose: () => void;
}

export const MeetingInfoModal = (props: MeetingInfoModalProps) => {
  const { eventInfo, handleModalClose } = props;

  return (
    <ModalSkeleton
      title={eventInfo.subject}
      handleModalClose={handleModalClose}
    >
      <h3 className={styles.subtitleInfo}>
        Start:<span>{format(eventInfo.startTime, "HH:mm")}</span>
      </h3>
      <h3 className={styles.subtitleInfo}>
        End:<span>{format(eventInfo.endTime, "HH:mm")}</span>
      </h3>
      <h3 className={styles.subtitleInfo}>
        Organizer:<span>{eventInfo.organizer}</span>
      </h3>
    </ModalSkeleton>
  );
};
