// react-scheduler/src/components/room_status/progress_bar/radial_separators/RadialSeparators.tsx
import styles from "./RadialSeparators.module.scss";

interface SeparatorProps {
  turns: number;
}

const Separator = (props: SeparatorProps) => {
  const { turns } = props;
  return (
    <div
      style={{
        transform: `rotate(${turns}turn)`,
      }}
      className={styles.separator}
    ></div>
  );
};

interface RadialSeparators {
  count: number;
}

export const RadialSeparators = (props: RadialSeparators) => {
  const { count } = props;
  const countForMirroringSeparators = count / 2 - 1;
  const turns = 1 / countForMirroringSeparators;

  return (
    <>
      {Array.from(Array(countForMirroringSeparators).keys()).map(
        (index: number) => (
          <Separator key={index} turns={index * turns} />
        )
      )}
    </>
  );
};

// vue-scheduler/src/components/room_status_components/progress_bar_components/RadialSeparators.vue
<script setup lang="ts">
import SeparatorComponent from './SeparatorComponent.vue';
interface RadialSeparatorsProps {
  count: number;
}
const props = defineProps<RadialSeparatorsProps>();

const countForMirroringSeparators = props.count / 2 - 1;
const turns = 1 / countForMirroringSeparators;

const separatorKeys = Array.from(Array(countForMirroringSeparators).keys());
</script>

<template>
  <div :class="$style.radialSeparatorsContainer">
    <SeparatorComponent
      v-for="(key, idx) in separatorKeys"
      :key="idx"
      :turns="idx * turns"
    ></SeparatorComponent>
  </div>
</template>

<style lang="scss" module>
.radialSeparatorsContainer {
  position: relative;
  width: 100%;
  height: 100%;
  top: -50%;
  left: 100%;
  transform: translate(-50%, -50%);
}
</style>
