// react-scheduler/src/components/scheduler/event_components/singular_event_wrapper/SingularEventWrapper.tsx
import { EventInfo } from "../../../../types/EventInfo";
import { Event } from "../event_component/Event";
import styles from "./SingularEventWrapper.module.scss";

interface SingularEventWrapperProps {
  topOffset: number;
  eventHeight: number;
  eventInfo: EventInfo;
}

export const SingularEventWrapper = (props: SingularEventWrapperProps) => {
  const { topOffset, eventHeight, eventInfo } = props;
  return (
    <div
      className={styles.eventWrapper}
      style={{ top: `${topOffset}px`, height: `${eventHeight}px` }}
    >
      <Event eventInfo={eventInfo} />
    </div>
  );
};

// vue-scheduler/src/components/scheduler_components/event_components/SingularEventWrapper.vue
<script setup lang="ts">
import type { EventInfo } from '@/types/EventInfo';

interface SingularEventWrapperProps {
  topOffset: number;
  eventHeight: number;
  eventInfo: EventInfo;
}

const props = defineProps<SingularEventWrapperProps>();
const { topOffset, eventHeight, eventInfo } = props;
</script>

<template>
  <div :class="$style.eventWrapper" :style="{ top: `${topOffset}px`, height: `${eventHeight}px` }">
    <Event :eventInfo="eventInfo" />
  </div>
</template>

<style lang="scss" module>
.eventWrapper {
  position: absolute;
  width: 80%;
  margin-left: calc(var(--item-gap-size) * 2.5);
  margin-right: var(--item-gap-size);
}
</style>
