// vue-scheduler/src/components/scheduler_components/timeline_components/TimelineComponent.vue
<script setup lang="ts">
import TimelineElement from './TimelineElement.vue';
import { timeFormatting } from '../../../helpers/scheduler_helper';

const workDayStart = 8;
const workDayEnd = 20;
const workDayHours: number[] = [];
for (let n = workDayStart; n <= workDayEnd - 1; n++) workDayHours.push(n);
</script>

<template>
  <div :class="$style.timelineContainer">
    <TimelineElement v-for="n in workDayHours" :key="n" :currentHour="timeFormatting(n)" />
  </div>
</template>

<style lang="scss" module>
.timelineContainer {
  height: 600px;
}
</style>

// react-scheduler/src/components/scheduler/timeline/Timeline.tsx
import { timeFormatting } from "../../../helpers/scheduler_helper";
import styles from "./Timeline.module.scss";

interface TimelineElementProps {
  currentHour: string;
}
const TimelineElement = (props: TimelineElementProps) => {
  const { currentHour } = props;
  return (
    <div className={styles.timelineElementContainer}>
      {currentHour}
      <div className={styles.singularLine}></div>
    </div>
  );
};

export const Timeline = () => {
  const generateTimelines = () => {
    const timelines: JSX.Element[] = [];
    const workDayStart = 8;
    const workDayEnd = 20;

    for (let i = workDayStart; i <= workDayEnd - 1; i++) {
      timelines.push(
        <TimelineElement key={`line-${i}`} currentHour={timeFormatting(i)} />
      );
    }

    return timelines;
  };

  return <div className={styles.timelineContainer}>{generateTimelines()}</div>;
};
