// vue-scheduler/src/components/room_status_components/RoomStatus.vue
<script setup lang="ts">
import { handleTimeUntilFree } from '@/helpers/room_status_helper';
import ColorWaves from './ColorWaves.vue';
import ProgressBar from './progress_bar_components/ProgressBar.vue';
import type { EventInfo } from '@/types/EventInfo';
import { ref, watchEffect } from 'vue';

interface RoomStatusProps {
  currentEvent: EventInfo | null;
  currentMoment: Date;
  isLoading: boolean;
  isError: boolean;
}
const props = defineProps<RoomStatusProps>();
const { currentEvent, currentMoment, isLoading, isError } = props;

const initProgressBarValue = 100;
const progressBarValue = ref(100);

watchEffect(() => {
  if (currentEvent === null) {
    progressBarValue.value = initProgressBarValue;
  }
});

const handleProgressBarUpdate = () => {
  if (!currentEvent) return;
  const { minutesUntilFree, totalMeetingTime } = handleTimeUntilFree(currentEvent, currentMoment);
  const value = Math.round(
    initProgressBarValue - (initProgressBarValue * minutesUntilFree) / totalMeetingTime
  );

  if (value <= 100 && value !== progressBarValue.value) progressBarValue.value = value;
};

handleProgressBarUpdate();
</script>

<template>
  <div :class="$style.roomStatusWrapper">
    <ColorWaves :isBooked="false" />
    <ProgressBar
      :value="progressBarValue"
      :isLoading="isLoading"
      :isError="isError"
      :isBooked="!!currentEvent"
    />
  </div>
</template>

<style lang="scss" module>
.roomStatusWrapper {
  width: 100%;
  justify-self: center;
  aspect-ratio: 1/1;
  position: relative;
  padding: 0.75rem;
  color: var(--clr-white);
  overflow: hidden;
}
</style>

// react-scheduler/src/components/room_status/RoomStatus.tsx
import { useEffect, useState } from "react";
import { EventInfo } from "../../types/EventInfo";
import { handleTimeUntilFree } from "../../helpers/room_status_helper";
import styles from "./RoomStatus.module.scss";
import { ColorWaves } from "./color_waves/ColorWaves";
import { ProgressBar } from "./progress_bar/ProgressBar";

interface RoomStatusProps {
  events: EventInfo[];
  currentEvent: EventInfo | null;
  currentMoment: Date;
  isLoading: boolean;
  isError: boolean;
}

export const RoomStatus = (props: RoomStatusProps) => {
  const initProgressBarValue = 100;
  const { currentEvent, currentMoment, isLoading, isError } = props;

  const [progressBarValue, setProgressBarValue] = useState<number>(100);

  useEffect(() => {
    if (currentEvent === null) resetRoomState();
  }, [currentEvent]);

  const resetRoomState = () => {
    setProgressBarValue(initProgressBarValue);
  };

  const handleProgressBarUpdate = () => {
    if (!currentEvent) return;
    const { minutesUntilFree, totalMeetingTime } = handleTimeUntilFree(
      currentEvent,
      currentMoment
    );
    const value = Math.round(
      initProgressBarValue -
        (initProgressBarValue * minutesUntilFree) / totalMeetingTime
    );

    if (value <= 100 && value !== progressBarValue) setProgressBarValue(value);
  };

  handleProgressBarUpdate();
  return (
    <div className={styles.roomStatusWrapper}>
      <ColorWaves isBooked={!!currentEvent} />
      <ProgressBar
        value={progressBarValue}
        isBooked={!!currentEvent}
        isLoading={isLoading}
        isError={isError}
      />
    </div>
  );
};
